var dadJokes = [
  ["What did one pirate say to the other when he beat him at chess?", "Checkmatey!"],
  ["I burned 2000 calories today...", "I left my food in the oven for too long!"],
  ["I broke my arm in two places!", "My doctor told me to stop going to those places!"],
  ["I quit my job at the coffee shop the other day.", "It was just the same old grind over and over!"],
  ["I never buy anything that has Velcro with it...", "It's a total rip-off!"],
  ["I used to work at a soft drink can crushing company...", "It was soda pressing!"],
  ["I wondered why the frisbee kept on getting bigger.", "Then it hit me!"],
  ["I was going to tell you a fighting joke...", "But I forgot the punch line!"],
  ["What is the most groundbreaking invention of all time?", "The shovel!"],
  ["Did you hear about that famous Italian chef who died?", "He pasta way!"],
  ["I could never be a plumber.", "It's too hard watching your life's work go down the drain!"],
  ["What kind of music do astronauts listen to?", "Neptunes!"],
  ["What is the only concert in the world that costs 45 cents?", "50 Cent, featuring Nickelback!"],
  ["My wife recently went on a tropical food diet and now our house is full of this stuff.", "It's enough to make a mango crazy!"],
  ["Want to hear a construction joke?", "Nevermind, I'm still working on it!"],
  ["I burnt my Hawaiian pizza today in the oven...", "I should have cooked it on aloha temperature!"],
  ["Anyone can be buried when they die...", "But if you want to be cremated then you have to urn it!"],
  ["Where do pirates get their hooks?", "Second hand stores!"],
  ["Why did Shakespeare's wife leave him?", "She got sick of all the drama!"],
  ["I just bought a dictionary, but all of the pages are blank.", "I have no words!"],
  ["Want to hear a joke about going to the bathroom?", "Urine for a treat!"],
  ["I'm reading a book about anti-gravity.", "It's impossible to put down!"],
  ["You're American when you go into the bathroom, and you're American when you come out, but do you know what you are while you're in there?", "European!"],
  ["Want to hear a joke about a piece of paper?", "Nevermind. It's tearable!"],
  ["If you see a robbery at an Apple Store what are you?", "An iWitness!"],
  ["How do you make a tissue dance?", "Put a little boogie in it!"],
  ["Why did the invisible man turn down the job offer?", "He couldn't see himself doing it!"],
  ["How do you make holy water?", "You boil the hell out of it!"],
  ["Did you hear about the circus fire?", "It was in tents!"],
  ["How many tickles does it take to make an octopus laugh?", "Ten-tickles!"],
  ["Why did the cow in the pasture get promoted at work?", "Because he is OUT-STANDING in his field!"],
  ["What do prisoners use to call each other?", "Cell phones!"],
  ["Why couldn't the bike standup by itself?", "It was two tired!"],
  ["You know what the loudest pet you can get is?", "A trumpet!"],
  ["What do you get when you cross a snowman with a vampire?", "Frostbite!"],
  ["Can February March?", "No, but April May!"],
  ["What do you call a lonely cheese?", "Provolone!"],
  ["Why can't you hear a pterodactyl go to the bathroom?", "Because the pee is silent!"],
  ["What did the buffalo say to his son when he dropped him off at school?", "Bison!"],
  ["What do you call someone with no body and no nose?", "Nobody knows!"],
  ["Why did the crab never share?", "Because he's shellfish!"],
  ["How do you get a squirrel to like you?", "Act like a nut!"],
  ["Why don't eggs tell jokes?", "They'd crack each other up!"],
  ["Why can't a nose be 12 inches long?", "Because then it would be a foot!"],
  ["Did you hear the rumor about butter?", "Well, I'm not going to spread it!"],
  ["What do you call an elephant that doesn't matter?", "An irrelephant!"],
  ["What do you get from a pampered cow?", "Spoiled milk!"],
  ["What's the best way to watch a fly fishing tournament?", "Live stream!"],
  ["When does a joke become a dad joke?", "When it becomes apparent!"],
  ["What's an astronaut's favorite part of a computer?", "The space bar!"],
  ["What did the shy pebble wish for?", "That he was a little boulder!"],
  ["Did you hear about the guy whose whole left side was cut off?", "He's all right now!"],
  ["Why didn't the skeleton cross the road?", "Because he had no guts!"],
  ["What did one nut say as he chased another nut?", "I'm a cashew!"],
  ["How come the stadium got hot after the game?", "Because all of the fans left!"],
  ["Why was it called the dark ages?", "Because of all the knights!"],
  ["Why did the tomato blush?", "Because it saw the salad dressing!"],
  ["What creature is smarter than a talking parrot?", "A spelling bee!"],
  ["Why did the kid cross the playground?", "To get to the other slide!"],
  ["Why does a Moon-rock taste better than an Earth-rock?", "Because it's a little meteor!"],
  ["How many South Americans does it take to change a lightbulb?", "A Brazilian!"],
  ["What is the difference between ignorance and apathy?", "I don't know and I don't care!"],
  ["What did Romans use to cut pizza before the rolling cutter?", "Lil Caesars!"],
  ["Why should you never take advice from electrons?", "Because they are always negative!"],
  ["Why should you never trust atoms?", "Because they make up everything!"],
  ["What did the beaver say to the tree?", "It's been nice gnawing you!"],
  ["What did the late tomato say to the early tomato?", "I'll ketchup!"],
  ["When is a door not a door?", "When it's ajar!"],
  ["What kind of music do mummy's like?", "Rap!"],
  ["Why should you never trust a pig with a secret?", "Because it's bound to squeal!"],
  ["Why are mummys scared of vacation?", "They're afraid to unwind!"],
  ["What kind of tree fits in your hand?", "A palm tree!"],
  ["What musical instrument is found in the bathroom?", "A tuba toothpaste!"],
  ["What do you call corn that joins the army?", "Kernel!"],
  ["Why did Microsoft PowerPoint cross the road?", "To get to the other slide!"],
  ["What did one toilet say to the other?", "You look a bit flushed!"],
  ["Why did the picture go to jail?", "Because it was framed!"],
  ["What did one wall say to the other wall?", "I'll meet you at the corner!"],
  ["Why was the broom late?", "It over swept!"],
  ["What has four wheels and flies?", "A garbage truck!"],
  ["Why did the scarecrow win an award?", "Because he was outstanding in his field!"],
  ["Why did the coffee file a police report?", "It got mugged!"],
  ["What did the grape do when he got stepped on?", "He let out a little wine!"],
  ["Did you hear about the kidnapping at school?", "It's fine, he woke up!"],
  ["How does a penguin build it's house?", "Igloos it together!"],
  ["Did you hear about the restaurant on the moon?", "Great food, no atmosphere!"],
  ["What happens when a frog's car dies?", "He needs a jump. If that doesn't work he has to get it toad!"],
  ["What did the flowers do when the bride walked down the aisle?", "They rose!"],
  ["Why is Peter Pan always flying?", "Because he Neverlands!"],
  ["Which state has the most streets?", "Rhode Island!"],
  ["Why was the color green notoriously single?", "It was always so jaded!"],
  ["How do celebrities stay cool?", "They have many fans!"],
  ["What's the most depressing day of the week?", "Sadder day!"],
  ["Dogs can't operate MRI machines", "But catscan!"],
  ["What kind of car does a sheep like to drive?", "A lamborghini!"],
  ["What did the accountant say while auditing a document?", "This is taxing!"],
  ["What did the two pieces of bread say on their wedding day?", "It was loaf at first sight!"],
  ["What do you call a toothless bear?", "A gummy bear!"],
  ["What is a child guilty of if they refuse to nap?", "Resisting a rest!"],
  ["I know a lot of jokes about retired people...", "But none of them work!"],
  ["What does a house wear?", "Address!"],
  ["What do you call an unpredictable camera?", "A loose Canon!"],
  ["Which U.S. state is known for its especially small soft drinks?", "Minnesota!"],
  ["What do sprinters eat before a race?", "Nothing. They fast!"],
  ["Why shouldn't you write with a broken pencil?", "Because it's pointless!"],
  ["What's the most patriotic sport?", "Flag football!"],
  ["Why did the farmer decide to try a career in music?", "Because he had a ton of sick beets!"],
  ["Which days are the strongest? Saturday and Sunday.", "The rest are weekdays!"],
  ["How do cows stay up to date?", "They read the Moo-spaper!"],
  ["What's the difference between a well-dressed man on a unicycle and a poorly-dressed man on a bicycle?", "Attire!"],
  ["Who were the greenest Presidents in US history?", "The bushes!"],
  ["How does cereal pay its bills?", "With Chex!"],
  ["What did Yoda say when he saw himself in 4K?", "HD, am I?"],
  ["How do flat-earthers travel?", "On a plane!"],
  ["Why did the clock get kicked out of the library?", "It tocked too much!"],
  ["Why do we tell actors to break a leg?", "Because every show has a cast!"],
  ["Why was the egg thrown away after it heard a joke?", "It cracked up!"],
  ["Why can't a leopard hide?", "They're always spotted!"],
  ["Why are fish so smart?", "They live in schools!"],
  ["What's the best thing about Switzerland?", "I don't know, but the flag is a big plus!"],
  ["Did you hear that one about the roof?", "Nevermind, it's over your head!"],
  ["How do you deal with a fear of speed bumps?", "You slowly get over it!"],
  ["I'd avoid the sushi if I were you.", "It's a little fishy!"],
  ["What happens when a snowman throws a tantrum?", "He has a meltdown!"],
  ["What did the ocean say to the beach?", "Nothing, it just waved!"],
  ["What do you call a sleeping bull?", "A bulldozer!"],
  ["How do you throw a party in outer space?", "You planet!"],
  ["What do you say to a rabbit on its birthday?", "Hoppy Birthday!"],
  ["What do you call a fake noodle?", "An impasta!"],
];

function getRandomInt(min, max) {
  min = Math.ceil(min);
  max = Math.floor(max);
  return Math.floor(Math.random() * (max - min) + min);
}

window.onload = function() {
  let num = getRandomInt(0, dadJokes.length-1);
  document.getElementById("djLine").innerText = dadJokes[num][0];
  document.getElementById("djAnswer").innerText = dadJokes[num][1];
}
